In [ ]:
import pandas as pd 
from fuzzywuzzy import process
from fuzzywuzzy import fuzz
df = pd.read_csv("../data/raw/Offerings_2019-10-25.csv")

In [ ]:
list_of_vars = ['sponsor', 
                'sponsor_experience', 
                'offering', 
                'offering_city', 
                'offering_state',
                'property_type', 
                'investment_structure', 
                'investment_profile',
                'investor_accreditation',
                '1031_exchange',
                'opportunity_zone',
                'offering_status',
               ]


def lower_and_strip_vars(df, list_of_vars):
    df.columns = df.columns.str.strip().str.lower()\
        .str.replace(' ', '_')\
        .str.replace('?', '')\
        .str.replace('(', '')\
        .str.replace(')', '')\
        .str.replace('%', 'pct')\
        .str.replace('-', '_')\
        .str.replace('$', 'dollars')
    for var in list_of_vars:
        df[var] = df[var].str.lower()
        df[var] = df[var].str.strip()
    return df

In [ ]:
df = lower_and_strip_vars(df=df,list_of_vars=list_of_vars)

In [ ]:
date_vars = ['date_closed', 
             'targeted_first_distribution_date', 
             'date_funds_due',
             'first_distribution_period_end_date',
             'first_distribution_payment_date', 
             'last_distribution_period_end_date',
             'last_tax_document_date',
             'disposition_date', 
             'last_distribution_payment_date',
            ]
def change_to_date_datatypes(df, date_vars):
    for var in date_vars:
        df[var] = pd.to_datetime(df[var])
    return df



df = change_to_date_datatypes(df=df, date_vars=date_vars)

In [ ]:
df.head()

In [ ]:
def standardize_object_vars():
    return None

In [ ]:
df.iloc[:, 0:1].head(10)

In [ ]:
choices = list(df['sponsor'].unique())

In [ ]:
df['sponsor'].value_counts().head(20)

In [ ]:
process.extract("rhodium capital advisors", choices, scorer=fuzz.token_sort_ratio)

In [ ]:
def explore_column_w_fuzzwuzzy(df, column):
    choices = list(df[column].unique())
    fuzzy_matches = {}
    for value in choices:
         fuzzy_matches[value] = process.extract(str(value), choices, scorer=fuzz.token_sort_ratio)
    return fuzzy_matches

### already checked the follwing text variables to clean

* sponsor

In [280]:
df.head()

,sponsor,sponsor_experience,offering,offering_city,offering_state,property_type,investment_structure,investment_profile,targeted_investor_irr_pct,targeted_investor_equity_multiple,...,offering_status,first_distribution_period_end_date,first_distribution_payment_date,last_distribution_period_end_date,last_distribution_payment_date,last_tax_document_date,realized_investor_equity_multiple,realized_avg_annual_cash_yield_pct,disposition_date,realized_investor_irr_pct
0,crowdstreet investments,blended,crowdstreet blended portfolio - series v,NaN,or,multi-use,equity fund,value add,18.0,2.0,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
1,crowdstreet advisors,blended,private managed accounts by crowdstreet advisors,portland,oregon,multi-use,equity fund,value add,NaN,NaN,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
2,crowdstreet advisors,blended,crowdstreet opportunity zone portfolio,NaN,u.s.,multi-use,equity,opportunistic,10.0,2.0,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
3,trion properties,seasoned,meadows apartments,newark,ca,multifamily,equity,value add,15.9,1.5,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
4,capstone realty group,tenured,1700 palm beach lakes,west palm beach,fl,office,equity,value add,19.1,2.0,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN

In [293]:
fuzzy_matches = explore_column_w_fuzzwuzzy(df=df, column='offering_state')

In [303]:
df['offering_state'].value_counts().tail(20)

al                3
in                3
wi                3
ok                3
mn                2
dc                2
ct                2
la                2
nm                2
md                2
usa               1
iowa              1
colorado          1
ar                1
ms                1
nv                1
north carolina    1
vt                1
oregon            1
ut                1
Name: offering_state, dtype: int64

In [301]:
fuzzy_matches['oregon']

[('oregon', 100), ('or', 50), ('colorado', 43), ('nc', 25), ('ga', 25)]

In [297]:
def clean_dirty_column(df, var, string):
    contains_str = df[var].str.contains(string)
    df[var] = np.where(contains_str, string, df[var])
    return df

In [298]:
df = clean_dirty_column(df=df,var='offering_city', string='multiple')
df = clean_dirty_column(df=df,var='offering_city', string='new york')
df = clean_dirty_column(df=df,var='offering_city', string='atlanta')


df = clean_dirty_column(df=df,var='offering_state', string='multiple')

In [292]:
df['']

,sponsor,sponsor_experience,offering,offering_city,offering_state,property_type,investment_structure,investment_profile,targeted_investor_irr_pct,targeted_investor_equity_multiple,...,offering_status,first_distribution_period_end_date,first_distribution_payment_date,last_distribution_period_end_date,last_distribution_payment_date,last_tax_document_date,realized_investor_equity_multiple,realized_avg_annual_cash_yield_pct,disposition_date,realized_investor_irr_pct
0,crowdstreet investments,blended,crowdstreet blended portfolio - series v,multiple,multiple,multi-use,equity fund,value add,18.00,2.00,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
1,crowdstreet advisors,blended,private managed accounts by crowdstreet advisors,portland,oregon,multi-use,equity fund,value add,NaN,NaN,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
2,crowdstreet advisors,blended,crowdstreet opportunity zone portfolio,multiple,multiple,multi-use,equity,opportunistic,10.00,2.00,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
3,trion properties,seasoned,meadows apartments,newark,ca,multifamily,equity,value add,15.90,1.50,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
4,capstone realty group,tenured,1700 palm beach lakes,west palm beach,fl,office,equity,value add,19.10,2.00,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
5,westpac,tenured,elevation at okemos (ph ii),okemos,mi,multifamily,equity,development,18.00,1.60,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
6,cascadia senior living & development,seasoned,fieldstone memory care - puyallup,puyallup,wa,senior housing,equity,development,22.50,1.80,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
7,one real estate investment,seasoned,axiom apartments charlotte,charlotte,nc,multifamily,equity,core plus,14.70,1.90,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
8,ssi,tenured,61 state street,charleston,sc,hospitality,preferred equity,value add,17.40,1.90,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
9,middleburg real estate partners,tenured,mosby riverlights,wilmington,north carolina,multifamily,equity,development,20.40,1.70,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
10,flywheel capital partners,emerging,colorado springs office portfolio,colorado springs,colorado,office,equity,core plus,18.60,2.10,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
11,block funds,tenured,villas at waterside,lenexa,ks,multifamily,equity,opportunistic,13.50,3.60,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
12,bridgeview,seasoned,bv multifamily fund i,multiple,multiple,multi-use,equity fund,opportunistic,22.00,2.88,...,closed,2017-12-31,2017-12-07,2019-06-30,2019-08-01,2019-05-17,0.03,NaN,NaT,NaN
13,block funds,tenured,westowne center retail,west des moines,iowa,multifamily,equity,core plus,19.40,2.20,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
14,liquid capital,emerging,avia riverside apartments,roswell,ga,multifamily,equity,value add,18.90,1.90,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
15,vertical ventures,seasoned,vertical ventures fund i,greater sf bay area,ca,multi-use,equity fund,opportunistic,19.00,2.00,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
16,mcfarlin group,seasoned,the ivy of mckinney,mckinney,tx,senior housing,equity,value add,19.10,2.00,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
17,crowdstreet investments,blended,crowdstreet blended portfolio - summer 2019,multiple,multiple,multi-use,equity fund,value add,18.00,2.50,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
18,trueline capital,emerging,trueline capital fund ii,pacific northwest,multiple,residential,debt fund,core plus,11.00,1.20,...,closed,2016-01-31,2016-01-07,2019-09-30,2019-10-16,2019-05-28,0.21,NaN,NaT,NaN
19,gwr equities,seasoned,trails at city park,houston,tx,multifamily,equity,value add,15.20,2.50,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
20,rhodium capital advisors,seasoned,summit ridge apartments,charlotte,nc,multifamily,equity,value add,19.80,1.90,...,closed,2019-09-30,2019-10-10,2019-09-30,2019-10-10,NaT,0.01,NaN,NaT,NaN
21,denholtz properties,tenured,deerfield corporate park,deerfield beach,fl,office,equity,core plus,15.00,1.90,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
22,insite group,tenured,holiday inn & suites across from universal orl...,orlando,fl,hospitality,equity,value add,18.50,2.10,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
23,emerald equity group,seasoned,the crest at princeton meadows,plainsboro,nj,multifamily,equity,core plus,16.00,2.30,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
24,prp,tenured,nobu restaurant dc,washington,dc,retail,equity,value add,14.30,1.80,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
25,rhodium capital advisors,seasoned,the willows apartments,kileen,tx,multifamily,equity,value add,18.00,1.80,...,closed,2019-09-30,2019-10-10,2019-09-30,2019-10-10,NaT,0.01,NaN,NaT,NaN
26,driftwood,tenured,ft. lauderdale opportunity zone hotel,fort lauderdale,fl,hospitality,equity,development,12.70,2.50,...,funding,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
27,phoenix development,seasoned,226 w. jackson: dual branded hilton canopy and...,chicago,il,hospitality,equity,opportunistic,24.10,4.20,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
28,presidio companies,tenured,home2 suites,west sacramento,ca,hospitality,equity,development,18.60,3.50,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
29,guefen development,tenured,haven at denton,denton,tx,multifamily,equity,opportunistic,20.60,1.80,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,mascia development,seasoned,val verde place,la vista,ne,retail,equity,value add,15.80,1.95,...,closed,1900-01-02,1900-01-02,2018-06-30,2018-06-15,2018-03-10,0.11,0.32,NaT,NaN
295,virtua partners,emerging,plymouth meeting,plymouth meeting,pa,hospitality,equity,value add,21.70,2.40,...,closed,NaT,NaT,NaT,NaT,2018-05-25,NaN,NaN,NaT,NaN
296,brooklyn standard properties,emerging,west 107th,new york,ny,multifamily,equity,value add,14.00,1.60,...,closed,2016-12-31,2017-01-26,2017-03-31,2017-05-04,2019-03-14,0.01,0.04,NaT,NaN
297,"smartcap, inc.",seasoned,south seattle business park,seattle,wa,mixed use,equity,value add,20.40,2.30,...,realized,2016-09-30,2016-10-20,2019-05-24,2019-05-24,2019-03-14,2.31,6.92,NaT,70.19
298,denholtz properties,tenured,490 first avenue,st. petersburg,fl,office,equity,value add,19.70,2.30,...,realized,2016-06-30,2016-06-30,2019-06-30,2019-06-30,2019-03-28,1.57,4.70,2018-12-17,28.52
299,encore enterprises,tenured,encore gp acquisition fund ii,multiple,multiple,multi-use,equity fund,opportunistic,24.00,2.10,...,closed,2017-02-28,2017-12-31,2019-09-30,2019-09-30,2019-09-10,0.02,0.06,NaT,NaN
300,emerge investments,emerging,ivy at clear creek,houston,tx,multifamily,equity,value add,19.60,2.24,...,realized,2016-06-30,2016-07-20,2019-05-01,2019-06-25,2018-04-02,1.69,5.08,NaT,28.71
301,intellistay hospitality,emerging,intellistay boonville,boonville,mo,hospitality,equity,value add,24.30,2.40,...,closed,2016-04-30,2016-04-01,2019-08-31,2019-08-01,2019-09-09,0.54,1.63,NaT,NaN
302,cadence asset management,seasoned,cadence retail income fund,multiple,multiple,multi-use,equity fund,value add,15.00,2.01,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
303,denholtz properties,tenured,100 east pine street,orlando,fl,office,equity,value add,17.60,2.08,...,closed,2016-03-31,2016-03-31,2019-09-29,2019-09-30,2019-03-07,0.72,2.15,NaT,NaN
304,virtua partners,emerging,britannia business center i,pleasanton,ca,office,equity,opportunistic,30.00,2.20,...,closed,NaT,NaT,NaT,NaT,2018-05-24,NaN,NaN,NaT,NaN
305,keystone property group,tenured,1200 corporate place,boca raton,fl,office,preferred equity,core plus,14.40,1.82,...,closed,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaN
306,urban green,seasoned,welbrook santa monica memory care,santa monica,ca,senior housing,equity,opportunistic,22.10,2.60,...,closed,NaT,NaT,NaT,NaT,2019-04-10,NaN,NaN,NaT,NaN
307,global senior housing,emerging,new haven assisted living,spring,tx,senior housing,preferred equity,opportunistic,24.30,2.10,...,closed,2015-12-31,2015-12-31,2018-03-31,2018-03-31,2019-03-15,0.24,0.71,NaT,NaN
308,encore enterprises,tenured,harrisonburg doubletree,harrisonburg,va,hospitality,equity,value add,19.50,2.20,...,closed,2018-03-31,2018-03-31,2019-09-30,2019-09-30,2019-09-06,0.05,0.15,NaT,NaN
309,hayman properties,seasoned,abb corporate,westerville,oh,office,equity,value add,17.50,1.57,...,closed,2016-03-31,2016-04-20,2018-04-19,2018-04-19,2019-07-27,0.18,0.54,NaT,NaN
310,olympus property,tenured,olympus fund iv,multiple,multiple,multi-use,equity fund,core,11.41,7.80,...,closed,2015-02-28,2015-05-01,2019-03-31,2019-03-31,2019-10-03,0.32,0.96,NaT,NaN
311,westmount realty equities,tenured,westmount at colonnade,grand prairie,tx,multifamily,equity,value add,18.30,2.09,...,realized,2015-12-31,2016-01-26,2018-12-20,2019-01-31,2019-10-14,1.52,4.55,NaT,16.75
312,kleban properties,seasoned,2321 university blvd,tuscaloosa,al,mixed use,equity,value add,19.30,2.10,...,closed,2016-03-31,2016-03-31,2017-06-30,2017-06-30,2019-03-06,0.38,1.13,NaT,NaN
313,bancroft,tenured,sixth avenue west,golden,co,office,equity,value add,17.00,1.90,...,closed,2015-12-31,2016-02-09,2016-12-31,2017-02-15,2018-03-20,0.11,0.45,NaT,NaN
314,westmount realty equities,tenured,westmount at summer cove,grand prairie,tx,multifamily,equity,value add,18.00,2.00,...,closed,2015-12-31,2016-02-04,2019-06-30,2019-07-25,2019-10-14,0.29,1.16,NaT,NaN
315,capital real estate,tenured,ponderosa ranch fka sienna apartments,tempe,az,multifamily,equity,value add,17.00,2.03,...,closed,2015-01-31,2015-10-23,2018-10-24,2018-10-24,2019-03-05,0.84,3.36,NaT,NaN
316,aldwin apartments,emerging,oak chase,fort worth,tx,multifamily,equity,value add,16.50,1.81,...,closed,2015-12-31,2016-02-02,2019-06-30,2019-07-31,2018-04-03,0.58,2.34,NaT,NaN
317,phoinix capital partners,emerging,1380 garnet retail center,san diego,ca,retail,equity,opportunistic,23.70,1.53,...,closed,NaT,NaT,NaT,NaT,2018-03-21,NaN,NaN,NaT,NaN
318,"the william warren group, inc.",tenured,storquest: tempe / warner (1063),tempe,az,storage,equity,core plus,12.10,2.40,...,closed,2015-06-30,2015-07-15,2018-12-31,2019-01-15,2019-03-08,0.28,1.12,NaT,NaN
319,mainstreet,seasoned,mainstreet bloomington,bloomington,in,senior housing,mezzanine debt,core plus,14.00,1.30,...,realized,2014-06-30,2014-09-30,2018-08-15,2018-08-15,NaT,1.12,4.47,NaT,3.00
320,"windmill investments, llc",seasoned,timber oaks apartments,midlothian,tx,multifamily,equity,value add,17.80,2.14,...,realized,2015-03-31,2015-05-15,2018-09-19,2018-09-19,2019-03-26,1.63,6.51,NaT,19.83
321,aldwin apartments,emerging,villas at leblanc park,fort worth,tx,multifamily,equity,value add,19.60,1.73,...,realized,2015-06-30,2015-07-29,2017-12-31,2017-12-12,2018-04-03,1.42,5.69,NaT,17.79
322,urban green,seasoned,1924 franklin,oakland,ca,office,equity,value add,18.10,1.60,...,realized,2016-01-31,2016-12-12,2016-01-31,2016-12-12,2019-04-03,0.25,1.01,NaT,-26.85
323,everwest real estate partners,tenured,30 knightsbridge rd,piscataway,nj,office,mezzanine debt,core plus,10.50,1.64,...,closed,2015-03-31,2015-01-08,2019-03-31,2019-04-01,2019-03-29,0.39,1.57,NaT,NaN